<?php
/**
 * SharedlinksApi
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Alfresco\Api;

use \Alfresco\ApiClient;
use \Alfresco\ApiException;
use \Alfresco\Configuration;
use \Alfresco\ObjectSerializer;

/**
 * SharedlinksApi Class Doc Comment
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SharedlinksApi
{
    /**
     * API Client
     *
     * @var \Alfresco\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Alfresco\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Alfresco\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Alfresco\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Alfresco\ApiClient $apiClient set the API client
     *
     * @return SharedlinksApi
     */
    public function setApiClient(\Alfresco\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createSharedLink
     *
     * Create a shared link to a file
     *
     * @param \Alfresco\Model\SharedLinkBodyCreate $shared_link_body_create The nodeId to create a shared link for. (required)
     * @param string[] $include Returns additional information about the shared link, the following optional fields can be requested: * allowableOperations * path (optional)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return \Alfresco\Model\SharedLinkEntry
     */
    public function createSharedLink($shared_link_body_create, $include = null, $fields = null)
    {
        list($response) = $this->createSharedLinkWithHttpInfo($shared_link_body_create, $include, $fields);
        return $response;
    }

    /**
     * Operation createSharedLinkWithHttpInfo
     *
     * Create a shared link to a file
     *
     * @param \Alfresco\Model\SharedLinkBodyCreate $shared_link_body_create The nodeId to create a shared link for. (required)
     * @param string[] $include Returns additional information about the shared link, the following optional fields can be requested: * allowableOperations * path (optional)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of \Alfresco\Model\SharedLinkEntry, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSharedLinkWithHttpInfo($shared_link_body_create, $include = null, $fields = null)
    {
        // verify the required parameter 'shared_link_body_create' is set
        if ($shared_link_body_create === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_link_body_create when calling createSharedLink');
        }
        // parse inputs
        $resourcePath = "/shared-links";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if (is_array($include)) {
            $include = $this->apiClient->getSerializer()->serializeCollection($include, 'csv', true);
        }
        if ($include !== null) {
            $queryParams['include'] = $this->apiClient->getSerializer()->toQueryValue($include);
        }
        // query params
        if (is_array($fields)) {
            $fields = $this->apiClient->getSerializer()->serializeCollection($fields, 'csv', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = $this->apiClient->getSerializer()->toQueryValue($fields);
        }
        // body params
        $_tempBody = null;
        if (isset($shared_link_body_create)) {
            $_tempBody = $shared_link_body_create;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Alfresco\Model\SharedLinkEntry',
                '/shared-links'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Alfresco\Model\SharedLinkEntry', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\SharedLinkEntry', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation deleteSharedLink
     *
     * Deletes a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return void
     */
    public function deleteSharedLink($shared_id)
    {
        list($response) = $this->deleteSharedLinkWithHttpInfo($shared_id);
        return $response;
    }

    /**
     * Operation deleteSharedLinkWithHttpInfo
     *
     * Deletes a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSharedLinkWithHttpInfo($shared_id)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling deleteSharedLink');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/shared-links/{sharedId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation emailSharedLink
     *
     * Email shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param \Alfresco\Model\SharedLinkBodyEmail $shared_link_body_email The shared link email to send. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return void
     */
    public function emailSharedLink($shared_id, $shared_link_body_email)
    {
        list($response) = $this->emailSharedLinkWithHttpInfo($shared_id, $shared_link_body_email);
        return $response;
    }

    /**
     * Operation emailSharedLinkWithHttpInfo
     *
     * Email shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param \Alfresco\Model\SharedLinkBodyEmail $shared_link_body_email The shared link email to send. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function emailSharedLinkWithHttpInfo($shared_id, $shared_link_body_email)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling emailSharedLink');
        }
        // verify the required parameter 'shared_link_body_email' is set
        if ($shared_link_body_email === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_link_body_email when calling emailSharedLink');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}/email";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($shared_link_body_email)) {
            $_tempBody = $shared_link_body_email;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/shared-links/{sharedId}/email'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getSharedLink
     *
     * Get a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return \Alfresco\Model\SharedLinkEntry
     */
    public function getSharedLink($shared_id, $fields = null)
    {
        list($response) = $this->getSharedLinkWithHttpInfo($shared_id, $fields);
        return $response;
    }

    /**
     * Operation getSharedLinkWithHttpInfo
     *
     * Get a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of \Alfresco\Model\SharedLinkEntry, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedLinkWithHttpInfo($shared_id, $fields = null)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling getSharedLink');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if (is_array($fields)) {
            $fields = $this->apiClient->getSerializer()->serializeCollection($fields, 'csv', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = $this->apiClient->getSerializer()->toQueryValue($fields);
        }
        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Alfresco\Model\SharedLinkEntry',
                '/shared-links/{sharedId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Alfresco\Model\SharedLinkEntry', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\SharedLinkEntry', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getSharedLinkContent
     *
     * Get shared link content
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param bool $attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response. (optional, default to true)
     * @param \DateTime $if_modified_since Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return void
     */
    public function getSharedLinkContent($shared_id, $attachment = 'true', $if_modified_since = null)
    {
        list($response) = $this->getSharedLinkContentWithHttpInfo($shared_id, $attachment, $if_modified_since);
        return $response;
    }

    /**
     * Operation getSharedLinkContentWithHttpInfo
     *
     * Get shared link content
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param bool $attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response. (optional, default to true)
     * @param \DateTime $if_modified_since Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedLinkContentWithHttpInfo($shared_id, $attachment = 'true', $if_modified_since = null)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling getSharedLinkContent');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}/content";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($attachment !== null) {
            $queryParams['attachment'] = $this->apiClient->getSerializer()->toQueryValue($attachment);
        }
        // header params
        if ($if_modified_since !== null) {
            $headerParams['If-Modified-Since'] = $this->apiClient->getSerializer()->toHeaderValue($if_modified_since);
        }
        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/shared-links/{sharedId}/content'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getSharedLinkRendition
     *
     * Get shared link rendition information
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string $rendition_id The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return \Alfresco\Model\RenditionEntry
     */
    public function getSharedLinkRendition($shared_id, $rendition_id)
    {
        list($response) = $this->getSharedLinkRenditionWithHttpInfo($shared_id, $rendition_id);
        return $response;
    }

    /**
     * Operation getSharedLinkRenditionWithHttpInfo
     *
     * Get shared link rendition information
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string $rendition_id The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of \Alfresco\Model\RenditionEntry, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedLinkRenditionWithHttpInfo($shared_id, $rendition_id)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling getSharedLinkRendition');
        }
        // verify the required parameter 'rendition_id' is set
        if ($rendition_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $rendition_id when calling getSharedLinkRendition');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}/renditions/{renditionId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }
        // path params
        if ($rendition_id !== null) {
            $resourcePath = str_replace(
                "{" . "renditionId" . "}",
                $this->apiClient->getSerializer()->toPathValue($rendition_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Alfresco\Model\RenditionEntry',
                '/shared-links/{sharedId}/renditions/{renditionId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Alfresco\Model\RenditionEntry', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\RenditionEntry', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getSharedLinkRenditionContent
     *
     * Get shared link rendition content
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string $rendition_id The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     * @param bool $attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response. (optional, default to true)
     * @param \DateTime $if_modified_since Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return void
     */
    public function getSharedLinkRenditionContent($shared_id, $rendition_id, $attachment = 'true', $if_modified_since = null)
    {
        list($response) = $this->getSharedLinkRenditionContentWithHttpInfo($shared_id, $rendition_id, $attachment, $if_modified_since);
        return $response;
    }

    /**
     * Operation getSharedLinkRenditionContentWithHttpInfo
     *
     * Get shared link rendition content
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @param string $rendition_id The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     * @param bool $attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response. (optional, default to true)
     * @param \DateTime $if_modified_since Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedLinkRenditionContentWithHttpInfo($shared_id, $rendition_id, $attachment = 'true', $if_modified_since = null)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling getSharedLinkRenditionContent');
        }
        // verify the required parameter 'rendition_id' is set
        if ($rendition_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $rendition_id when calling getSharedLinkRenditionContent');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}/renditions/{renditionId}/content";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($attachment !== null) {
            $queryParams['attachment'] = $this->apiClient->getSerializer()->toQueryValue($attachment);
        }
        // header params
        if ($if_modified_since !== null) {
            $headerParams['If-Modified-Since'] = $this->apiClient->getSerializer()->toHeaderValue($if_modified_since);
        }
        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }
        // path params
        if ($rendition_id !== null) {
            $resourcePath = str_replace(
                "{" . "renditionId" . "}",
                $this->apiClient->getSerializer()->toPathValue($rendition_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/shared-links/{sharedId}/renditions/{renditionId}/content'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation listSharedLinkRenditions
     *
     * List renditions for a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return \Alfresco\Model\RenditionPaging
     */
    public function listSharedLinkRenditions($shared_id)
    {
        list($response) = $this->listSharedLinkRenditionsWithHttpInfo($shared_id);
        return $response;
    }

    /**
     * Operation listSharedLinkRenditionsWithHttpInfo
     *
     * List renditions for a shared link
     *
     * @param string $shared_id The identifier of a shared link to a file. (required)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of \Alfresco\Model\RenditionPaging, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSharedLinkRenditionsWithHttpInfo($shared_id)
    {
        // verify the required parameter 'shared_id' is set
        if ($shared_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $shared_id when calling listSharedLinkRenditions');
        }
        // parse inputs
        $resourcePath = "/shared-links/{sharedId}/renditions";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($shared_id !== null) {
            $resourcePath = str_replace(
                "{" . "sharedId" . "}",
                $this->apiClient->getSerializer()->toPathValue($shared_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Alfresco\Model\RenditionPaging',
                '/shared-links/{sharedId}/renditions'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Alfresco\Model\RenditionPaging', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\RenditionPaging', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation listSharedLinks
     *
     * List shared links
     *
     * @param int $skip_count The number of entities that exist in the collection before those included in this list.  If not supplied then the default value is 0. (optional, default to 0)
     * @param int $max_items The maximum number of items to return in the list.  If not supplied then the default value is 100. (optional, default to 100)
     * @param string $where Optionally filter the list by \&quot;sharedByUser\&quot; userid of person who shared the link (can also use -me-)  *   &#x60;&#x60;&#x60;where&#x3D;(sharedByUser&#x3D;&#39;jbloggs&#39;)&#x60;&#x60;&#x60;  *   &#x60;&#x60;&#x60;where&#x3D;(sharedByUser&#x3D;&#39;-me-&#39;)&#x60;&#x60;&#x60; (optional)
     * @param string[] $include Returns additional information about the shared link, the following optional fields can be requested: * allowableOperations * path (optional)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return \Alfresco\Model\SharedLinkPaging
     */
    public function listSharedLinks($skip_count = '0', $max_items = '100', $where = null, $include = null, $fields = null)
    {
        list($response) = $this->listSharedLinksWithHttpInfo($skip_count, $max_items, $where, $include, $fields);
        return $response;
    }

    /**
     * Operation listSharedLinksWithHttpInfo
     *
     * List shared links
     *
     * @param int $skip_count The number of entities that exist in the collection before those included in this list.  If not supplied then the default value is 0. (optional, default to 0)
     * @param int $max_items The maximum number of items to return in the list.  If not supplied then the default value is 100. (optional, default to 100)
     * @param string $where Optionally filter the list by \&quot;sharedByUser\&quot; userid of person who shared the link (can also use -me-)  *   &#x60;&#x60;&#x60;where&#x3D;(sharedByUser&#x3D;&#39;jbloggs&#39;)&#x60;&#x60;&#x60;  *   &#x60;&#x60;&#x60;where&#x3D;(sharedByUser&#x3D;&#39;-me-&#39;)&#x60;&#x60;&#x60; (optional)
     * @param string[] $include Returns additional information about the shared link, the following optional fields can be requested: * allowableOperations * path (optional)
     * @param string[] $fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter. (optional)
     * @throws \Alfresco\ApiException on non-2xx response
     * @return array of \Alfresco\Model\SharedLinkPaging, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSharedLinksWithHttpInfo($skip_count = '0', $max_items = '100', $where = null, $include = null, $fields = null)
    {
        if (!is_null($skip_count) && ($skip_count < 0)) {
            throw new \InvalidArgumentException('invalid value for "$skip_count" when calling SharedlinksApi.listSharedLinks, must be bigger than or equal to 0.');
        }

        if (!is_null($max_items) && ($max_items < 1)) {
            throw new \InvalidArgumentException('invalid value for "$max_items" when calling SharedlinksApi.listSharedLinks, must be bigger than or equal to 1.');
        }

        // parse inputs
        $resourcePath = "/shared-links";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($skip_count !== null) {
            $queryParams['skipCount'] = $this->apiClient->getSerializer()->toQueryValue($skip_count);
        }
        // query params
        if ($max_items !== null) {
            $queryParams['maxItems'] = $this->apiClient->getSerializer()->toQueryValue($max_items);
        }
        // query params
        if ($where !== null) {
            $queryParams['where'] = $this->apiClient->getSerializer()->toQueryValue($where);
        }
        // query params
        if (is_array($include)) {
            $include = $this->apiClient->getSerializer()->serializeCollection($include, 'csv', true);
        }
        if ($include !== null) {
            $queryParams['include'] = $this->apiClient->getSerializer()->toQueryValue($include);
        }
        // query params
        if (is_array($fields)) {
            $fields = $this->apiClient->getSerializer()->serializeCollection($fields, 'csv', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = $this->apiClient->getSerializer()->toQueryValue($fields);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Alfresco\Model\SharedLinkPaging',
                '/shared-links'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Alfresco\Model\SharedLinkPaging', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\SharedLinkPaging', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Alfresco\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
