<?php
/**
 * NodeBodyLock
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Alfresco\Model;

use \ArrayAccess;

/**
 * NodeBodyLock Class Doc Comment
 *
 * @category    Class
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NodeBodyLock implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'NodeBodyLock';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'time_to_expire' => 'int',
        'type' => 'string',
        'lifetime' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'time_to_expire' => null,
        'type' => null,
        'lifetime' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'time_to_expire' => 'timeToExpire',
        'type' => 'type',
        'lifetime' => 'lifetime'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'time_to_expire' => 'setTimeToExpire',
        'type' => 'setType',
        'lifetime' => 'setLifetime'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'time_to_expire' => 'getTimeToExpire',
        'type' => 'getType',
        'lifetime' => 'getLifetime'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const TYPE_ALLOW_OWNER_CHANGES = 'ALLOW_OWNER_CHANGES';
    const TYPE_FULL = 'FULL';
    const LIFETIME_PERSISTENT = 'PERSISTENT';
    const LIFETIME_EPHEMERAL = 'EPHEMERAL';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_ALLOW_OWNER_CHANGES,
            self::TYPE_FULL,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getLifetimeAllowableValues()
    {
        return [
            self::LIFETIME_PERSISTENT,
            self::LIFETIME_EPHEMERAL,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['time_to_expire'] = isset($data['time_to_expire']) ? $data['time_to_expire'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : 'ALLOW_OWNER_CHANGES';
        $this->container['lifetime'] = isset($data['lifetime']) ? $data['lifetime'] : 'PERSISTENT';
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if (!is_null($this->container['time_to_expire']) && ($this->container['time_to_expire'] < 0)) {
            $invalid_properties[] = "invalid value for 'time_to_expire', must be bigger than or equal to 0.";
        }

        $allowed_values = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getLifetimeAllowableValues();
        if (!in_array($this->container['lifetime'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'lifetime', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['time_to_expire'] < 0) {
            return false;
        }
        $allowed_values = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getLifetimeAllowableValues();
        if (!in_array($this->container['lifetime'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets time_to_expire
     * @return int
     */
    public function getTimeToExpire()
    {
        return $this->container['time_to_expire'];
    }

    /**
     * Sets time_to_expire
     * @param int $time_to_expire
     * @return $this
     */
    public function setTimeToExpire($time_to_expire)
    {

        if (!is_null($time_to_expire) && ($time_to_expire < 0)) {
            throw new \InvalidArgumentException('invalid value for $time_to_expire when calling NodeBodyLock., must be bigger than or equal to 0.');
        }

        $this->container['time_to_expire'] = $time_to_expire;

        return $this;
    }

    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type
     * @return $this
     */
    public function setType($type)
    {
        $allowed_values = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets lifetime
     * @return string
     */
    public function getLifetime()
    {
        return $this->container['lifetime'];
    }

    /**
     * Sets lifetime
     * @param string $lifetime
     * @return $this
     */
    public function setLifetime($lifetime)
    {
        $allowed_values = $this->getLifetimeAllowableValues();
        if (!is_null($lifetime) && !in_array($lifetime, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'lifetime', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['lifetime'] = $lifetime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Alfresco\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Alfresco\ObjectSerializer::sanitizeForSerialization($this));
    }
}


