<?php
/**
 * PermissionElement
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Alfresco\Model;

use \ArrayAccess;

/**
 * PermissionElement Class Doc Comment
 *
 * @category    Class
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PermissionElement implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PermissionElement';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'authority_id' => 'string',
        'name' => 'string',
        'access_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'authority_id' => null,
        'name' => null,
        'access_status' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'authority_id' => 'authorityId',
        'name' => 'name',
        'access_status' => 'accessStatus'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'authority_id' => 'setAuthorityId',
        'name' => 'setName',
        'access_status' => 'setAccessStatus'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'authority_id' => 'getAuthorityId',
        'name' => 'getName',
        'access_status' => 'getAccessStatus'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const ACCESS_STATUS_ALLOWED = 'ALLOWED';
    const ACCESS_STATUS_DENIED = 'DENIED';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getAccessStatusAllowableValues()
    {
        return [
            self::ACCESS_STATUS_ALLOWED,
            self::ACCESS_STATUS_DENIED,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['authority_id'] = isset($data['authority_id']) ? $data['authority_id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['access_status'] = isset($data['access_status']) ? $data['access_status'] : 'ALLOWED';
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = $this->getAccessStatusAllowableValues();
        if (!in_array($this->container['access_status'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'access_status', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = $this->getAccessStatusAllowableValues();
        if (!in_array($this->container['access_status'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets authority_id
     * @return string
     */
    public function getAuthorityId()
    {
        return $this->container['authority_id'];
    }

    /**
     * Sets authority_id
     * @param string $authority_id
     * @return $this
     */
    public function setAuthorityId($authority_id)
    {
        $this->container['authority_id'] = $authority_id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets access_status
     * @return string
     */
    public function getAccessStatus()
    {
        return $this->container['access_status'];
    }

    /**
     * Sets access_status
     * @param string $access_status
     * @return $this
     */
    public function setAccessStatus($access_status)
    {
        $allowed_values = $this->getAccessStatusAllowableValues();
        if (!is_null($access_status) && !in_array($access_status, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'access_status', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['access_status'] = $access_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Alfresco\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Alfresco\ObjectSerializer::sanitizeForSerialization($this));
    }
}


