<?php
/**
 * ErrorErrorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfresco;

/**
 * ErrorErrorTest Class Doc Comment
 *
 * @category    Class */
// * @description ErrorError
/**
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorErrorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorError"
     */
    public function testErrorError()
    {
    }

    /**
     * Test attribute "error_key"
     */
    public function testPropertyErrorKey()
    {
    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "brief_summary"
     */
    public function testPropertyBriefSummary()
    {
    }

    /**
     * Test attribute "stack_trace"
     */
    public function testPropertyStackTrace()
    {
    }

    /**
     * Test attribute "description_url"
     */
    public function testPropertyDescriptionUrl()
    {
    }

    /**
     * Test attribute "log_id"
     */
    public function testPropertyLogId()
    {
    }
}
