<?php
/**
 * NodeBodyCreateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco\Core
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfresco\Core;

/**
 * NodeBodyCreateTest Class Doc Comment
 *
 * @category    Class */
// * @description NodeBodyCreate
/**
 * @package     Alfresco\Core
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NodeBodyCreateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NodeBodyCreate"
     */
    public function testNodeBodyCreate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "node_type"
     */
    public function testPropertyNodeType()
    {
    }

    /**
     * Test attribute "aspect_names"
     */
    public function testPropertyAspectNames()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "relative_path"
     */
    public function testPropertyRelativePath()
    {
    }

    /**
     * Test attribute "association"
     */
    public function testPropertyAssociation()
    {
    }

    /**
     * Test attribute "secondary_children"
     */
    public function testPropertySecondaryChildren()
    {
    }

    /**
     * Test attribute "targets"
     */
    public function testPropertyTargets()
    {
    }
}
