<?php
/**
 * RequestHighlightTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfresco;

/**
 * RequestHighlightTest Class Doc Comment
 *
 * @category    Class */
// * @description Request that highlight fragments to be added to result set rows The properties reflect SOLR highlighting parameters.
/**
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestHighlightTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestHighlight"
     */
    public function testRequestHighlight()
    {
    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {
    }

    /**
     * Test attribute "postfix"
     */
    public function testPropertyPostfix()
    {
    }

    /**
     * Test attribute "snippet_count"
     */
    public function testPropertySnippetCount()
    {
    }

    /**
     * Test attribute "fragment_size"
     */
    public function testPropertyFragmentSize()
    {
    }

    /**
     * Test attribute "max_analyzed_chars"
     */
    public function testPropertyMaxAnalyzedChars()
    {
    }

    /**
     * Test attribute "merge_contiguous"
     */
    public function testPropertyMergeContiguous()
    {
    }

    /**
     * Test attribute "use_phrase_highlighter"
     */
    public function testPropertyUsePhraseHighlighter()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }
}
