<?php
/**
 * ResultSetContextTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfresco;

/**
 * ResultSetContextTest Class Doc Comment
 *
 * @category    Class */
// * @description Context that applies to the whole result set
/**
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultSetContextTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultSetContext"
     */
    public function testResultSetContext()
    {
    }

    /**
     * Test attribute "consistency"
     */
    public function testPropertyConsistency()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "facet_queries"
     */
    public function testPropertyFacetQueries()
    {
    }

    /**
     * Test attribute "facets_fields"
     */
    public function testPropertyFacetsFields()
    {
    }

    /**
     * Test attribute "facets"
     */
    public function testPropertyFacets()
    {
    }

    /**
     * Test attribute "spellcheck"
     */
    public function testPropertySpellcheck()
    {
    }
}
