<?php
/**
 * ResultNodeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Alfresco;

/**
 * ResultNodeTest Class Doc Comment
 *
 * @category    Class */
// * @description ResultNode
/**
 * @package     Alfresco
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultNodeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultNode"
     */
    public function testResultNode()
    {
    }

    /**
     * Test attribute "search"
     */
    public function testPropertySearch()
    {
    }

    /**
     * Test attribute "archived_by_user"
     */
    public function testPropertyArchivedByUser()
    {
    }

    /**
     * Test attribute "archived_at"
     */
    public function testPropertyArchivedAt()
    {
    }

    /**
     * Test attribute "version_label"
     */
    public function testPropertyVersionLabel()
    {
    }

    /**
     * Test attribute "version_comment"
     */
    public function testPropertyVersionComment()
    {
    }
}
