<?php
/**
 * FavoritesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco\Core
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfresco\Core;

use \Alfresco\Core\Configuration;
use \Alfresco\Core\ApiClient;
use \Alfresco\Core\ApiException;
use \Alfresco\Core\ObjectSerializer;

/**
 * FavoritesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfresco\Core
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FavoritesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createFavorite
     *
     * Create a favorite.
     *
     */
    public function testCreateFavorite()
    {
    }

    /**
     * Test case for createSiteFavorite
     *
     * Create a site favorite.
     *
     */
    public function testCreateSiteFavorite()
    {
    }

    /**
     * Test case for deleteFavorite
     *
     * Delete a favorite.
     *
     */
    public function testDeleteFavorite()
    {
    }

    /**
     * Test case for deleteSiteFavorite
     *
     * Delete a site favorite.
     *
     */
    public function testDeleteSiteFavorite()
    {
    }

    /**
     * Test case for getFavorite
     *
     * Get a favorite.
     *
     */
    public function testGetFavorite()
    {
    }

    /**
     * Test case for getFavoriteSite
     *
     * Get a favorite site.
     *
     */
    public function testGetFavoriteSite()
    {
    }

    /**
     * Test case for listFavoriteSitesForPerson
     *
     * List favorite sites.
     *
     */
    public function testListFavoriteSitesForPerson()
    {
    }

    /**
     * Test case for listFavorites
     *
     * List favorites.
     *
     */
    public function testListFavorites()
    {
    }
}
