<?php
/**
 * NetworksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco\Core
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfresco\Core;

use \Alfresco\Core\Configuration;
use \Alfresco\Core\ApiClient;
use \Alfresco\Core\ApiException;
use \Alfresco\Core\ObjectSerializer;

/**
 * NetworksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfresco\Core
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getNetwork
     *
     * Get a network.
     *
     */
    public function testGetNetwork()
    {
    }

    /**
     * Test case for getNetworkForPerson
     *
     * Get network information.
     *
     */
    public function testGetNetworkForPerson()
    {
    }

    /**
     * Test case for listNetworksForPerson
     *
     * List network membership.
     *
     */
    public function testListNetworksForPerson()
    {
    }
}
