<?php
/**
 * NodesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfresco;

use \Alfresco\Configuration;
use \Alfresco\ApiClient;
use \Alfresco\ApiException;
use \Alfresco\ObjectSerializer;

/**
 * NodesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NodesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for copyNode
     *
     * Copy a node.
     *
     */
    public function testCopyNode()
    {
    }

    /**
     * Test case for createAssocation
     *
     * Create node association.
     *
     */
    public function testCreateAssocation()
    {
    }

    /**
     * Test case for createNode
     *
     * Create a node.
     *
     */
    public function testCreateNode()
    {
    }

    /**
     * Test case for createSecondaryChildAssocation
     *
     * Create secondary child.
     *
     */
    public function testCreateSecondaryChildAssocation()
    {
    }

    /**
     * Test case for deleteAssocation
     *
     * Delete node association(s).
     *
     */
    public function testDeleteAssocation()
    {
    }

    /**
     * Test case for deleteNode
     *
     * Delete a node.
     *
     */
    public function testDeleteNode()
    {
    }

    /**
     * Test case for deleteSecondaryChildAssocation
     *
     * Delete secondary child or children.
     *
     */
    public function testDeleteSecondaryChildAssocation()
    {
    }

    /**
     * Test case for getNode
     *
     * Get a node.
     *
     */
    public function testGetNode()
    {
    }

    /**
     * Test case for getNodeContent
     *
     * Get node content.
     *
     */
    public function testGetNodeContent()
    {
    }

    /**
     * Test case for listNodeChildren
     *
     * List node children.
     *
     */
    public function testListNodeChildren()
    {
    }

    /**
     * Test case for listParents
     *
     * List parents.
     *
     */
    public function testListParents()
    {
    }

    /**
     * Test case for listSecondaryChildren
     *
     * List secondary children.
     *
     */
    public function testListSecondaryChildren()
    {
    }

    /**
     * Test case for listSourceAssociations
     *
     * List source associations.
     *
     */
    public function testListSourceAssociations()
    {
    }

    /**
     * Test case for listTargetAssociations
     *
     * List target associations.
     *
     */
    public function testListTargetAssociations()
    {
    }

    /**
     * Test case for lockNode
     *
     * Lock a node.
     *
     */
    public function testLockNode()
    {
    }

    /**
     * Test case for moveNode
     *
     * Move a node.
     *
     */
    public function testMoveNode()
    {
    }

    /**
     * Test case for unlockNode
     *
     * Unlock a node.
     *
     */
    public function testUnlockNode()
    {
    }

    /**
     * Test case for updateNode
     *
     * Update a node.
     *
     */
    public function testUpdateNode()
    {
    }

    /**
     * Test case for updateNodeContent
     *
     * Update node content.
     *
     */
    public function testUpdateNodeContent()
    {
    }
}
