<?php
/**
 * RatingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **API**  Provides access to the features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfresco;

use \Alfresco\Configuration;
use \Alfresco\ApiClient;
use \Alfresco\ApiException;
use \Alfresco\ObjectSerializer;

/**
 * RatingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfresco
 * @author   Rhuan Barreto
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RatingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRating
     *
     * Create a rating.
     *
     */
    public function testCreateRating()
    {
    }

    /**
     * Test case for deleteRating
     *
     * Delete a rating.
     *
     */
    public function testDeleteRating()
    {
    }

    /**
     * Test case for getRating
     *
     * Get a rating.
     *
     */
    public function testGetRating()
    {
    }

    /**
     * Test case for listRatings
     *
     * List ratings.
     *
     */
    public function testListRatings()
    {
    }
}
