<?php
/**
 * TrashcanApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Alfresco
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alfresco Content Services REST API
 *
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Alfresco;

use \Alfresco\Configuration;
use \Alfresco\ApiClient;
use \Alfresco\ApiException;
use \Alfresco\ObjectSerializer;

/**
 * TrashcanApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alfresco
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TrashcanApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteDeletedNode
     *
     * Permanently delete a deleted node.
     *
     */
    public function testDeleteDeletedNode()
    {
    }

    /**
     * Test case for getArchivedNodeRendition
     *
     * Get rendition information for a deleted node.
     *
     */
    public function testGetArchivedNodeRendition()
    {
    }

    /**
     * Test case for getArchivedNodeRenditionContent
     *
     * Get rendition content of a deleted node.
     *
     */
    public function testGetArchivedNodeRenditionContent()
    {
    }

    /**
     * Test case for getDeletedNode
     *
     * Get a deleted node.
     *
     */
    public function testGetDeletedNode()
    {
    }

    /**
     * Test case for getDeletedNodeContent
     *
     * Get deleted node content.
     *
     */
    public function testGetDeletedNodeContent()
    {
    }

    /**
     * Test case for listDeletedNodeRenditions
     *
     * List renditions for a deleted node.
     *
     */
    public function testListDeletedNodeRenditions()
    {
    }

    /**
     * Test case for listDeletedNodes
     *
     * List deleted nodes.
     *
     */
    public function testListDeletedNodes()
    {
    }

    /**
     * Test case for restoreDeletedNode
     *
     * Restore a deleted node.
     *
     */
    public function testRestoreDeletedNode()
    {
    }
}
